# 《史记》知识库 - 用AI让历史书活起来

> 让历史研究不再是钻故纸堆，让"皓首穷经"不再必需

[![在线访问](https://img.shields.io/badge/在线访问-GitHub%20Pages-blue)](https://baojie.github.io/shiji-kb)
[![许可证](https://img.shields.io/badge/许可证-CC%20BY--NC--SA%204.0-orange)](LICENSE)

**在线Demo**：[首页](https://baojie.github.io/shiji-kb) · [五帝本纪](https://baojie.github.io/shiji-kb/chapters/001_五帝本纪.html) · [项羽本纪](https://baojie.github.io/shiji-kb/chapters/007_项羽本纪.html) · [秦楚之际月表](https://baojie.github.io/shiji-kb/chapters/016_秦楚之际月表.html) · [孔子世家](https://baojie.github.io/shiji-kb/chapters/047_孔子世家.html) · [刺客列传](https://baojie.github.io/shiji-kb/chapters/086_刺客列传.html)

---

## 项目愿景

**核心使命**：用AI让历史书"活"起来，让历史研究不再是钻故纸堆。

传统历史研究需要"皓首穷经"——终其一生钻研古籍，在浩如烟海的文献中寻找线索、发现规律。本项目通过AI Agent驱动的知识图谱化方法，将这一过程从数十年压缩到数周，让隐藏在历史文献中的规律和秘密更容易被发现。

**阅读革命的愿景**：

> 现在没有人再会读没有标点符号的文章，未来也不会有人愿意读没有语法加亮的文章。

正如标点符号让古文从"士大夫专利"变成"人人可读"，语法高亮将让历史文献从"专家研究对象"变成"大众认知工具"。

> **免责声明**：本项目由AI辅助生成，标注和知识提取中不可避免地存在错误和疏漏。我们正在与AI一起持续修正和完善这些问题——每一次迭代都会让数据质量更好一点。如发现错误，欢迎提交Issue帮助改进。本知识库严格局限于《史记》本身的文本内容，不涉及史实考证。

**关键突破**：

- 🤖 **AI驱动**：用Claude Code等AI Agent自动化处理古籍
- 🧠 **知识图谱化**：将文本转化为可查询、可分析的结构化知识
- 🎨 **认知辅助阅读**：借鉴IDE语法高亮和排版技术，通过颜色标注、结构化展示降低古文阅读门槛
  - **语法高亮是当代更强大的"标点符号"**：如同古代句读帮助断句，语法高亮用颜色和样式帮助理解语义
  - 实体语法高亮：15类实体不同颜色标注
  - 段落结构语义化：适当字体、缩进、分段、对齐降低认知负担
- 🔍 **发现隐藏规律**：通过数据分析揭示传统阅读难以发现的模式
- 🌐 **跨语言整合**：方法语言无关，可整合不同语种的历史知识
- 📚 **可扩展**：从史记到26史，再到全部古籍（4600万字→数亿字）

**当前成果（史记130篇）**：

- 📚 **文本标注**：130篇全部完成精细化语义标注
- 🏷️ **实体提取**：11,854个词条，96,591次标注（15类实体，含2026-03扩展典籍/礼仪/刑法/思想）
- 🔗 **实体索引**：15类实体索引页面（11,854条目），正文实体可点击跳转，别名合并（595条），语义消歧（644处），拼音排序导航
- 🕸️ **知识图谱**：人物、地名、官职、事件关系网络
- 📋 **事件索引**：130章全覆盖事件识别（3,185个事件，11类事件类型，含事件链分析）
- ⏱️ **事件年代标注**：3,051个事件标注公元纪年（98.7%覆盖），经五轮Agent反思审查修正~2,119处，积累26条错误模式+12条推理逻辑+35条细化模式
- 🔗 **事件关系**：7,652条关系（9种类型：延续/因果/跨章因果/包含/对立/互见/共人/共地/同期），1,876个跨线换乘
- 🗺️ **事件地铁图**：130条线路可视化，支持缩放/拖拽/搜索/实体链接/原文引用
- 📦 **知识单元（SKU）**：434个事实知识 + 241个技能知识 + 关系知识，含实体标注（394个SKU、7,497个实体关联）
- 🎮 **交互应用**：认知辅助阅读器（语法高亮+结构语义化）、事件地铁图、史记争霸游戏
- 🧠 **方法论Skills**：11个从实践中提炼的可复用方法论文档（详见下方）
- 📊 **分析方法**：统计分析、网络分析、时空分析

### 方法论 Skills（项目根目录）

从《史记》知识图谱化实践中提炼的11个可复用方法论，适用于其他古籍项目：

| SKILL | 说明 |
|-------|------|
| [古籍知识图谱化](SKILL_古籍知识图谱化.md) | 从《史记》项目中提炼的端到端方法论，适用于二十四史等大规模古籍处理 |
| [古籍章节切分与编号](SKILL_古籍章节切分与编号.md) | 篇章拆分、段落编号（Purple Numbers）和小节划分方法 |
| [古籍实体标注](SKILL_古籍实体标注.md) | 15类实体NER标注规范与流程（130篇×57万字实践，v2.0迁移为〖〗格式，官职符号`$`→`;`） |
| [古籍人名消歧](SKILL_实体消歧.md) | 4层启发式策略解决同名异指（3,797人名，644处消歧） |
| [古籍历史事件识别](SKILL_事件识别.md) | 从标注文本中识别和提取结构化历史事件记录 |
| [古籍事件提取与关系发现](SKILL_古籍事件提取与关系发现.md) | 3,185个事件和7,652条关系的提取与关系发现方法 |
| [事件年代推断](SKILL_事件年代推断.md) | 通过历史大事年表交叉验证，将纪年换算为公元前纪年 |
| [古籍年份消歧](SKILL_年份消歧.md) | 在位纪年→公元年三阶段消歧管线（380位君主，1,498条映射） |
| [古籍文本语义化](SKILL_古籍文本语义化.md) | 原始文本→标注Markdown：层级结构、段落编号、实体Token、对话拆分、NOTE块 |
| [区块与韵文处理](SKILL_区块与韵文处理.md) | ::: fenced div语义区块：太史公曰/赞/诗歌/引文等区块类型的标注与渲染规范 |
| [三家注标注](SKILL_三家注标注.md) | 《史记》三家注（集解/索隐/正义）语义化：数据结构、音韵注处理、书名标注、渲染设计 |

---

## 项目进展

### 当前状态（2026-03-13）

| 任务 | 进度 | 说明 |
|------|------|------|
| **文本标注** | 130/130 (100%) ✅ | 已完成全部130篇：本纪12篇、表10篇、书8篇、世家30篇、列传70篇 |
| **HTML生成** | 130/130 (100%) ✅ | 全部章节已生成HTML格式 |
| **十表渲染** | 10/10 (100%) ✅ | 十篇年表全部嵌入渲染（全视口宽度、sticky表头、实体标注） |
| **实体索引** | 15/15 (100%) ✅ | 15类实体索引页面，正文实体可点击跳转，别名合并（595条），语义消歧（644处） |
| **实体词表** | ✅ 完成 | 提取11,854个词条，96,591次标注 |
| **研究方法** | ✅ 完成 | 建立完整的数字人文研究方法体系 |

### 最新成果

#### 1. 实体分类词表（kg/vocabularies/）

从130个已标注章节中提取的完整词表：

| 类别 | 词条数 | 典型示例 |
|------|--------|----------|
| 👤 人名 | 4,176 | 孔子、项羽、项王 |
| 🗺️ 地名 | 1,880 | 咸阳、邯郸、长安 |
| 🎖️ 官职 | 1,418 | 丞相、太尉、将军 |
| 📅 时间 | 968 | 元年、正月、春秋 |
| 🏛️ 邦国 | — | 〖'汉〗、〖'周〗、〖'齐〗 |
| 👥 氏族 | — | 〖&刘氏〗、〖&嬴氏〗 |
| 📜 制度 | 678 | 郡县制、封禅、正朔 |
| 👥 族群 | 204 | 匈奴、夷狄、三苗 |
| 🏺 器物 | 914 | 鼎、玉璧、印绶 |
| ⭐ 天文 | 256 | 彗星、二十八宿、朔旦 |
| 🐉 神话 | 214 | 黄帝、女娲、禹 |
| 〘动植物〙 | 401 | 龙、凤、桑 |
| 《典籍》 | 48 | 春秋、尚书、诗经 |
| 〈礼仪〉 | 24 | 宗庙、籍田、郊祀 |
| 【刑法】 | 37 | 族诛、腰斩、黥刑 |
| 〔思想〕 | 52 | 仁义、礼乐、本纪 |

**详情参见**：[kg/vocabularies/README.md](kg/vocabularies/README.md)

#### 2. 研究方法体系

建立了完整的数字人文研究方法框架：

- 📖 [研究方法总则](doc/methodology/研究方法总则.md)：综合方法论
- 📋 [高级分析计划](doc/analysis/史记高级分析计划.md)：5阶段实施计划（v2.0）
- 📊 [统计分析报告](doc/analysis/史记统计分析.md)：全书统计数据
- 📐 [标注格式规范](doc/spec/标注格式规范.md)：含Lint规则
- 📝 [第一轮事件年代反思总结](doc/events/第一轮事件年代反思总结.md)：1,010处修正，25条新错误模式
- 📝 [第二轮事件年代反思总结](doc/events/第二轮事件年代反思总结.md)：431处修正，确定性升级+精细调校
- 📝 [第三轮事件年代反思总结](doc/events/第三轮事件年代反思总结.md)：465处修正，收敛验证+残留清理
- 📝 [第四轮事件年代反思总结](doc/events/第四轮事件年代反思总结.md)：167处修正，终态验证+格式统一
- 📝 [第五轮事件年代反思总结](doc/events/第五轮事件年代反思总结.md)：46处修正，跨章节交叉验证
- 📝 [事件年代反思创造过程详解](doc/events/事件年代反思创造过程详解.md)：五轮迭代方法论详解

#### 3. 分析工具

本项目采用 **AI Agent 驱动的数字人文研究范式**：

- 🤖 **Claude Code**：主要开发和分析工具
  - 实体标注系统开发
  - 批量文本处理
  - HTML生成工具链
  - 知识图谱构建

- 🔧 **Skills（技能）**：专门化任务处理
  - 文档标注技能
  - 数据提取技能
  - 可视化生成技能

- 🌐 **Multi-Agent协作**：复杂任务分解
  - 并行处理多个章节
  - 协同知识抽取
  - 质量控制验证

---

## 扩展计划

### 近期目标

- **表格交互化**：十表已完成渲染（[在线查看](tables/README.md)），待开发交互式查看器和JSON数据录入
- **知识图谱深化**：时间图谱（历法转换、多级时间粒度）、Neo4j图数据库

### 中期目标

- **二十六史**（约4000万字）：从史记扩展到全部正史
- **通鉴系列**（约600-700万字）：资治通鉴及续编

### 远期愿景

本项目验证的AI Agent驱动方法论，可推广到诸子百家、四库全书、佛道经典、诗词文集等大规模古籍数字化（总规模数亿字）。方法可复制、Agent驱动、Skills可复用。

---

## 目录结构

```
shiji-kb/
├── README.md                      # 项目说明
├── CHANGELOG.md                   # 更新日志
├── TODO.md                        # 任务清单
├── render_shiji_html.py           # 核心：Markdown→HTML渲染器
├── generate_all_chapters.py       # 批量生成全部130章HTML
├── publish_to_docs.sh             # 发布到GitHub Pages
├── sections_data.json             # 章节小节数据
│
├── chapter_md/                    # 标注后的Markdown文件（130/130 ✅）
│
├── docs/                          # GitHub Pages网站
│   ├── index.html                # 首页（瀑布流卡片布局）
│   ├── css/shiji-styles.css      # 样式表
│   ├── chapters/                 # HTML格式章节（130篇）
│   ├── entities/                 # 实体索引页面（15类+总览）
│   └── original_text/            # 130篇原始文本
│
├── kg/                           # 知识图谱（按知识类型组织）
│   ├── events/                   # 事件（3,185个事件 + 7,652条关系 + 年代审查）
│   │   ├── data/                # 130篇事件索引.md + event_relations.json
│   │   ├── reports/             # 反思结果JSON（130章×5轮）+ pipeline状态 + round1-4备份
│   │   └── scripts/             # 提取/标注/质检/反思管线/可视化脚本
│   ├── entities/                 # 实体（11,854条 + 别名/消歧，15类）
│   │   ├── data/                # entity_index.json, aliases, disambiguation
│   │   └── scripts/             # 索引/消歧/别名检测脚本
│   ├── chronology/              # 纪年（君主在位年 + 公元映射）
│   │   └── data/                # reign_periods.json, year_ce_map.json
│   ├── genealogy/               # 家谱（五帝/夏/商/周/秦/汉世系）
│   │   ├── data/                # 各朝代帝王家谱.md
│   │   └── scripts/             # 家族关系/世系提取
│   ├── relations/               # 人物关系（父子/母子/兄弟/君臣等）
│   ├── vocabularies/            # 词汇表（11类实体词表）
│   ├── flora_fauna/             # 动植物实体
│   └── rdf/                     # RDF/本体（ontology.ttl等）
│
├── ontology/                     # 标准知识单元（SKU）
│   └── skus/                    # 434 Factual + 241 Procedural + 1 Relational
│
├── scripts/                      # 通用工具脚本（非KG类）
│   ├── lint_markdown.py          # Markdown标注格式检查
│   ├── lint_html.py              # HTML输出格式检查
│   ├── analyze_word_frequency.py # 词频统计分析
│   └── ...                       # 其他辅助脚本
│
├── app/                          # 交互式应用
│   ├── metro/                    # 事件地铁图可视化
│   │   ├── index.html            # 地铁图前端（SVG, pan/zoom）
│   │   └── data/                 # metro_map_data.json
│   └── game/                     # 史记争霸游戏
│
├── doc/                          # 项目文档
│   ├── spec/                    # 格式规范（标注格式规范/实体标注方案/段落编号规范等）
│   ├── workflow/                 # 工作流程（开发工作流程/GitHub页面部署）
│   ├── methodology/              # 研究方法（研究方法总则/Markdown转化逻辑等）
│   ├── analysis/                 # 数据分析（统计分析/高级分析计划/词频统计等）
│   ├── events/                   # 事件年代（五轮反思总结/创造过程详解）
│   └── entities/                 # 实体标注（消歧别名报告/君主列表/表格计划等）
│
├── tables/                       # 十表数据（JSON+交互式HTML）
│
├── ref/                          # 参考文献（数字人文项目、学术研究、阅读价值）
│
├── resources/                    # 资源文件
│
└── temp/                         # 历史开发文件存档
```

---

## 研究方法

本项目采用AI Agent驱动的数字人文研究方法，核心工作流程：

### 1. 文本标注与结构化

- **实体标注**：16类实体精细标注（人名、地名、官职、时间、邦国、氏族、制度、族群、器物、天文、神话、动植物、典籍、礼仪、刑法、思想）
- **认知辅助阅读系统**：
  - **语法高亮——当代更强大的"标点符号"**：
    - 如同古代"句读"帮助断句理解，语法高亮用颜色和样式帮助理解语义结构
    - 为15类历史实体赋予不同颜色和视觉样式（人名蓝色、地名绿色、官职红色等）
    - 一眼识别关键信息：人物、地点、官职、时间等核心要素
    - 从"标点断句"进化到"语义着色"——认知辅助的革命性提升
  - **段落结构语义化**：进行段落结构的语义分析，优化视觉呈现
    - 适当的字体选择（正文、引文、注释使用不同字体）
    - 智能缩进（对话层级、列表结构用缩进表达）
    - 合理分段（长段落按语义拆分，提高可读性）
    - 视觉对齐（诗歌、表格、列表等结构化内容对齐显示）
  - **核心价值**：降低古文阅读认知负担，让读者轻松理解历史文献
  - **效果**：就像IDE帮助程序员理解代码，认知辅助系统帮助读者理解历史文献
- **段落编号**：Purple Numbers系统，支持精确引用和段落级导航
- **对话标识**：识别引语和对话内容，保留原文语境
- **格式转换**：Markdown → HTML，保持语义结构

### 2. 实体提取与词表构建
- **词表生成**：从130章节提取11,854个词条，96,591次标注
- **分类整理**：按15类实体分类，统计词频和分布
- **关系识别**：提取人物关系（家族、政治、师徒等）
- **家谱构建**：建立帝王世系图（五帝、夏、商、周、秦、汉）

### 3. 知识图谱构建
- **实体网络**：人名3,797个，地名1,880个，官职1,418个
- **关系抽取**：父子、母子、君臣、师徒等多种关系类型
- **事件识别**：从130章中提取结构化历史事件（战争、继位、政治、建设等11类），含事件链分析
- **数据组织**：结构化存储为Markdown和JSON格式
- **未来扩展**：计划导入Neo4j图数据库

### 4. 统计分析
- **文本规模**：130篇，总计约57.7万字（纯汉字576,915，含标点约70.6万字）
- **五体分布**：本纪13.3%、表12.2%、书7.2%、世家23.0%、列传44.2%
- **实体分布**：人名最多(4,176)，其次是地名(1,880)和官职(1,418)

### 5. 可视化展示
- **网页生成**：全部130章节HTML化，支持实体高亮和段落导航
- **交互功能**：可点击段落号、实体悬停提示、引语样式区分
- **GitHub Pages**：在线展示，公开访问

**核心特点**：使用Claude Code和AI Agent完成大部分开发和标注工作，强调可重复性和自动化

---

## 技术栈

### AI Agent 工具链

**核心平台**
- 🤖 **Claude Code**：AI驱动的开发环境
- 🧠 **Claude Sonnet 4.5 / Opus 4.6**：大语言模型（LLM）
- 🔧 **Claude Skills**：专门化任务技能
- 🌐 **Multi-Agent System**：并行协作架构

**Agent 能力**
- 📝 代码生成与编辑
- 🔍 文本分析与标注
- 📊 数据提取与转换
- 🧪 质量验证与测试
- 📖 文档生成与维护

### 辅助技术

**编程语言**
- 🐍 **Python 3.9+**：脚本开发
- 🌐 **JavaScript (ES6+)**：前端交互
- 📝 **Markdown**：文档标准

**数据格式**
- JSON：结构化数据
- Markdown：标注文本
- HTML/CSS：网页展示

**版本控制**
- Git/GitHub：代码管理
- GitHub Pages：静态网站托管

**未来扩展**
- Neo4j：知识图谱数据库
- D3.js：交互式可视化
- React：前端框架

---

## 使用方法

### 1. 克隆项目

```bash
git clone https://github.com/baojie/shiji-kb.git
cd shiji-kb
```

### 2. 安装依赖

```bash
pip install -r requirements.txt
```

### 3. 生成词表

```bash
python kg/vocabularies/scripts/build_vocabularies.py
```

### 4. 生成HTML

```bash
# 生成单个章节
python render_shiji_html.py chapter_md/001_五帝本纪.tagged.md

# 批量生成所有章节
python generate_all_chapters.py
```

### 5. 查看结果

- **在线访问**：https://baojie.github.io/shiji-kb
- **本地查看**：打开 `kg/vocabularies/README.md`

---

## 数据说明

### 实体标注规则

采用15类实体标注，使用特定符号标记（v2.0，2026-03迁移为〖〗格式）：

| 类别 | 标记 | 示例 |
|------|------|------|
| 人名 | `〖@〗` | 〖@秦始皇〗 |
| 地名 | `〖=〗` | 〖=咸阳〗 |
| 官职 | `〖;〗` | 〖;丞相〗 |
| 时间 | `〖%〗` | 〖%元年〗 |
| 邦国 | `〖'〗` | 〖'汉〗、〖'齐〗 |
| 氏族 | `〖&〗` | 〖&刘氏〗 |
| 制度 | `〖^〗` | 〖^郡县制〗 |
| 族群 | `〖~〗` | 〖~匈奴〗 |
| 器物 | `〖*〗` | 〖*鼎〗 |
| 天文 | `〖!〗` | 〖!彗星〗 |
| 神话 | `〚〛` | 〚黄帝〛 |
| 动植物 | `〘〙` | 〘龙〙 |
| 典籍 | `《》` | 《春秋》 |
| 礼仪 | `〈〉` | 〈宗庙〉 |
| 刑法 | `【】` | 【腰斩】 |
| 思想 | `〔〕` | 〔仁义〕 |

### 段落编号

采用圣经式编号（Biblical notation）：

```markdown
# [0] 章节名

## [1] 一级标题
[1.1] 段落内容...
[1.2] 段落内容...

## [2] 一级标题
### [2.1] 二级标题
[2.1.1] 段落内容...
```

---

## 项目统计

### 文本规模

- **总章节数**：130篇
- **总字数**：576,915字（约57.7万字，纯汉字；含标点约70.6万字）
- **已标注**：130篇（全部完成）✅
- **标注进度**：100% ✅

### 实体统计

- **词条总数**：11,854个
- **标注总数**：96,591次
- **人名**：3,566个
- **地名**：1,869个
- **官职**：2,303个
- **4类新增（2026-03）**：典籍46、礼仪22、刑法37、思想47

### 事件与关系

- **事件总数**：3,185个（130章全覆盖）
- **事件类型**：11类（战争、继位、政治、外交、建设等）
- **事件关系**：7,652条（自动5,126 + LLM 2,525）
- **关系类型**：9种（延续/因果/跨章因果/包含/对立/互见/共人/共地/同期）
- **跨章换乘**：1,876条
- **公元纪年**：3,051个事件已标注（98.7%覆盖，前2700年～前87年）
- **年代审查**：经五轮Agent反思修正~2,119处（1,010→431→465→167→46），积累SKILL规则26+12+35条

### 知识单元（SKU）

- **事实知识**：434个
- **技能知识**：241个
- **关系知识**：1个（含978条术语、1,336条三元组）
- **实体标注**：394个SKU、7,497个实体关联

### 方法论 Skills

- **项目级SKILL文档**：11个（古籍知识图谱化、章节切分、实体标注、人名消歧、年份消歧、事件识别、事件提取与关系发现、年代推断、文本语义化、区块与韵文处理、三家注标注）

### 五体分布

| 体裁 | 篇数 | 字数 | 占比 |
|------|------|------|------|
| 本纪 | 12 | 76,730 | 13.3% |
| 表 | 10 | 70,525 | 12.2% |
| 书 | 8 | 41,761 | 7.2% |
| 世家 | 30 | 132,853 | 23.0% |
| 列传 | 70 | 255,046 | 44.2% |

---

## TODO

- [x] ~~完成全部130章节标注~~ ✅ 已完成
- [x] ~~生成全部130章节HTML~~ ✅ 已完成
- [x] ~~命名实体索引系统~~ ✅ 15类实体索引页面+正文链接+别名合并
- [ ] 实施10大高级分析（使用Agent方法）
- [ ] 开发交互式可视化平台
- [ ] 构建Neo4j知识图谱数据库
- [ ] 完善知识图谱数据（关系、事件、时空）
- [ ] 撰写学术论文
- [ ] 发布开源数据集

**详细计划**参见：[史记高级分析计划.md](doc/analysis/史记高级分析计划.md)

---

## 贡献指南

欢迎各种形式的贡献：

### 参与方式

1. **知识图谱完善**：完善人物关系、事件抽取
2. **代码贡献**：改进分析脚本和工具
3. **学术讨论**：提供历史学、语言学见解
4. **可视化设计**：设计更好的数据呈现方式
5. **Bug报告**：发现问题请提issue

### 联系方式

- GitHub Issues：<https://github.com/baojie/shiji-kb/issues>（推荐）
- 微信：baojie_xigua
- 项目主页：<https://baojie.github.io/shiji-kb>

---

## 参考资源

### 数据来源
- 原始文本：https://ctext.org/shiji/zh
- 历史地图：中国历史地图集、谭其骧地理数据库

---

## 许可证

### 内容许可
- 标注数据：**CC BY-NC-SA 4.0**
  - 署名-非商业性使用-相同方式共享

### 代码许可
- 分析脚本：**MIT License**

### 原始文本
- 《史记》为公有领域作品
- 现代标点本版权归中华书局

---

## 致谢

感谢以下资源和工具的支持：

- **Claude Code & Claude Sonnet 4.5 / Opus 4.6**：项目主要开发工具和AI助手
- **中国哲学书电子化计划**（ctext.org）：原始文本来源
- **GitHub Pages**：网站托管服务
- **Netlify**：游戏部署平台
- 开源社区的各种优秀工具

---

## 更新日志

查看完整更新日志：[CHANGELOG.md](CHANGELOG.md)

### 最新进展 (2026-03-13)

- 🔄 **语义区块全面升级**：全书130篇从 `<h4>` 标题迁移至 `::: fenced div` 围栏块语法，83个章节自动补全太史公曰/赞标注，区块渲染改为tooltip，赞/诗歌保持硬换行。新增 [SKILL_区块与韵文处理.md](SKILL_区块与韵文处理.md)（方法论SKILL增至11个）
- 🔣 **v2.0实体标注符号迁移**：全部130篇标注符号从 `@X@` 等对称格式迁移至 `〖@X〗` 非对称〖〗格式，官职符号从 `$` 改为 `;`，消除与 Markdown 语法冲突
- 📚 **实体体系扩展至15类**：新增典籍（《》）、礼仪（〈〉）、刑法（【】）、思想（〔〕）四类实体；v2.0迁移后：11,854词条/96,591次标注
- 🔣 **标注符号迁移**：神话 `?X?` → `〚X〛`，动植物 `🌿X🌿` → `〘X〙`，全面切换至无歧义 CJK 标点符号体系

### 历史进展 (2026-03-11)

- ⏱️ **事件年代五轮反思审查**：Agent自动化反思管线对130章3,092个事件的年代标注进行五轮系统性审查，共修正~2,119处（1,010→431→465→167→46），年代覆盖率从25%提升至98.7%（3,051/3,092），积累26条错误模式+12条推理逻辑+35条细化模式写入SKILL文档，第五轮跨章节交叉验证确认数据稳定收敛
- 🗺️ **事件地铁图**：130条线路可视化3,185个事件，支持缩放拖拽、搜索、实体链接、原文引用、zoom-dependent标签
- 🔗 **事件关系系统**：7,652条关系（自动5,126 + LLM 2,525），9种类型，1,876个跨章换乘连接
- 📁 **KG目录重构**：按知识类型组织为7个子目录（events/entities/chronology/genealogy/relations/vocabularies/flora_fauna），各含data/scripts
- 📦 **知识单元（SKU）体系**：434个事实知识 + 241个技能知识，7,497个实体标注
- 🔗 **命名实体索引系统**：11类实体索引页面（11,000+条目），别名合并（586条），语义消歧（644处）

---

**项目维护者**：[baojie](https://github.com/baojie)
**最后更新**：2026-03-13

---

<p align="center">
  <strong>📖 让古老的历史以数字的方式重新焕发光彩 🌟</strong>
</p>
